version: '3'

services:
  db_mysql:
    image: mysql:5.7
    hostname: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=zGGiFtH0dYsjX7cgvin7
      - MYSQL_DATABASE=chat_app

  application:
    build: .
    hostname: rails
    command: /entrypoint.sh
    ports:
      - "3000:3000"
      - "1234:1234"
    depends_on:
      - db_mysql
      - elasticsearch
    volumes:
      - .:/chat_app
    tty: true
    environment:
      WAIT_HOSTS: db_mysql:3306, elasticsearch:9200, rabbitmq:5672
      APPLICATION_PORT: 3000
      DEBUGGING_PORT: 1234

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    ports:
      - "9200:9200"

  rabbitmq:
    image: rabbitmq:3.7