version: '3'

services:
  db_mysql:
    image: mysql:5.7
    hostname: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=zGGiFtH0dYsjX7cgvin7
      - MYSQL_DATABASE=chat_app

  application:
    build: .
    hostname: rails
    command: bin/rails server --port 3000 --binding 0.0.0.0
    ports:
      - "3000:3000"
    depends_on:
      - db_mysql
    volumes:
      - .:/chat_app
    restart: on-failure
    environment:
      WAIT_HOSTS: db_mysql:3306
